version: '3'
services:
  backend:
    build: ./backend
    ports:
      - 3001:3001
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
  mongodb:
    image: mongo
    command: --serviceExecutor adaptive
